import type { BehaviorContract } from '@/domain/types/configuration/faceted-cascade'

import {
  BehaviorContractKind,
  EndgeFacetType,
  FacetedCascadeEntityType,
  FacetedCascadeScope,
} from '@/domain/types/configuration/faceted-cascade'

export const COMPONENT_BEHAVIOR_CONTRACTS: BehaviorContract<FacetedCascadeEntityType>[] = [
  {
    facet: EndgeFacetType.Behavior,
    entityType: FacetedCascadeEntityType.Component,
    eventName: 'mounted',
    title: 'Component mounted',
    description: 'Подмена поведения после монтирования runtime компонента.',
    eventKind: BehaviorContractKind.Lifecycle,
    scope: FacetedCascadeScope.Owner,
    supportsEnvironmentOverride: true,
  },
  {
    facet: EndgeFacetType.Behavior,
    entityType: FacetedCascadeEntityType.Component,
    eventName: 'ready',
    title: 'Component ready',
    description: 'Подмена поведения после полной готовности компонента к взаимодействию.',
    eventKind: BehaviorContractKind.Lifecycle,
    scope: FacetedCascadeScope.Owner,
    supportsEnvironmentOverride: true,
  },
  {
    facet: EndgeFacetType.Behavior,
    entityType: FacetedCascadeEntityType.Component,
    eventName: 'click',
    title: 'Click',
    description: 'Подмена поведения при клике по компоненту.',
    eventKind: BehaviorContractKind.Interaction,
    scope: FacetedCascadeScope.Owner,
    supportsEnvironmentOverride: true,
  },
  {
    facet: EndgeFacetType.Behavior,
    entityType: FacetedCascadeEntityType.Component,
    eventName: 'input',
    title: 'Input',
    description: 'Подмена поведения при вводе значения в компонент.',
    eventKind: BehaviorContractKind.Interaction,
    scope: FacetedCascadeScope.Owner,
    supportsEnvironmentOverride: true,
  },
  {
    facet: EndgeFacetType.Behavior,
    entityType: FacetedCascadeEntityType.Component,
    eventName: 'change',
    title: 'Change',
    description: 'Подмена поведения при подтверждённом изменении значения компонента.',
    eventKind: BehaviorContractKind.Interaction,
    scope: FacetedCascadeScope.Owner,
    supportsEnvironmentOverride: true,
  },
  {
    facet: EndgeFacetType.Behavior,
    entityType: FacetedCascadeEntityType.Component,
    eventName: 'focus',
    title: 'Focus',
    description: 'Подмена поведения, когда компонент получает фокус.',
    eventKind: BehaviorContractKind.Interaction,
    scope: FacetedCascadeScope.Owner,
    supportsEnvironmentOverride: true,
  },
  {
    facet: EndgeFacetType.Behavior,
    entityType: FacetedCascadeEntityType.Component,
    eventName: 'blur',
    title: 'Blur',
    description: 'Подмена поведения, когда компонент теряет фокус.',
    eventKind: BehaviorContractKind.Interaction,
    scope: FacetedCascadeScope.Owner,
    supportsEnvironmentOverride: true,
  },
]
