import type { BehaviorContract } from '@/domain/types/configuration/faceted-cascade'

import {
  BehaviorContractKind,
  EndgeFacetType,
  FacetedCascadeEntityType,
  FacetedCascadeScope,
} from '@/domain/types/configuration/faceted-cascade'

export const QUERY_BEHAVIOR_CONTRACTS: BehaviorContract<FacetedCascadeEntityType>[] = [
  {
    facet: EndgeFacetType.Behavior,
    entityType: FacetedCascadeEntityType.Query,
    eventName: 'before-request',
    title: 'Before request',
    description: 'Подмена поведения перед отправкой запроса. Подходит для loading, трассировки и подготовки параметров.',
    eventKind: BehaviorContractKind.Data,
    scope: FacetedCascadeScope.Owner,
    supportsEnvironmentOverride: true,
  },
  {
    facet: EndgeFacetType.Behavior,
    entityType: FacetedCascadeEntityType.Query,
    eventName: 'success',
    title: 'Success',
    description: 'Подмена поведения при успешном завершении запроса.',
    eventKind: BehaviorContractKind.Data,
    scope: FacetedCascadeScope.Owner,
    supportsEnvironmentOverride: true,
  },
  {
    facet: EndgeFacetType.Behavior,
    entityType: FacetedCascadeEntityType.Query,
    eventName: 'error',
    title: 'Error',
    description: 'Подмена поведения при ошибке запроса.',
    eventKind: BehaviorContractKind.Data,
    scope: FacetedCascadeScope.Owner,
    supportsEnvironmentOverride: true,
  },
  {
    facet: EndgeFacetType.Behavior,
    entityType: FacetedCascadeEntityType.Query,
    eventName: 'settled',
    title: 'Settled',
    description: 'Подмена поведения после завершения запроса независимо от исхода.',
    eventKind: BehaviorContractKind.Data,
    scope: FacetedCascadeScope.Owner,
    supportsEnvironmentOverride: true,
  },
  {
    facet: EndgeFacetType.Behavior,
    entityType: FacetedCascadeEntityType.Query,
    eventName: 'cancelled',
    title: 'Cancelled',
    description: 'Подмена поведения при отмене запроса.',
    eventKind: BehaviorContractKind.Data,
    scope: FacetedCascadeScope.Owner,
    supportsEnvironmentOverride: true,
  },
  {
    facet: EndgeFacetType.Behavior,
    entityType: FacetedCascadeEntityType.Query,
    eventName: 'filter-change',
    title: 'Filter change',
    description: 'Подмена поведения при изменении связанного фильтра query.',
    eventKind: BehaviorContractKind.Interaction,
    scope: FacetedCascadeScope.Owner,
    supportsEnvironmentOverride: true,
  },
]
