import type { ConfigurationContract } from '@/domain/types/configuration/configuration-contract.types'

import {
  ConfigurationValueType,
} from '@/domain/types/configuration/configuration-contract.types'
import { DomainSectionType } from '@/domain/types/document/document.types'
import { EndgeFacetType, FacetedCascadeScope } from '@/domain/types/configuration/faceted-cascade'

export const NAVIGATION_CONFIGURATION_CONTRACTS: ConfigurationContract<DomainSectionType>[] = [
  {
    facet: EndgeFacetType.Configuration,
    entityType: DomainSectionType.Navigation,
    fieldPath: 'tree[*].title',
    title: 'Navigation item title',
    description: 'Отображаемый заголовок узла навигации. Может переопределяться по контексту без мутации base-дерева.',
    scope: FacetedCascadeScope.Target,
    valueType: ConfigurationValueType.String,
    supportsBinding: true,
    supportsEnvironmentOverride: true,
    supportsWatch: true,
    runtimeMutationPolicy: 'patch',
  },
  {
    facet: EndgeFacetType.Configuration,
    entityType: DomainSectionType.Navigation,
    fieldPath: 'tree[*].icon',
    title: 'Navigation item icon',
    description: 'Иконка конкретного узла навигации.',
    scope: FacetedCascadeScope.Target,
    valueType: ConfigurationValueType.String,
    supportsBinding: true,
    supportsEnvironmentOverride: true,
    supportsWatch: true,
    runtimeMutationPolicy: 'patch',
  },
  {
    facet: EndgeFacetType.Configuration,
    entityType: DomainSectionType.Navigation,
    fieldPath: 'tree[*].hidden',
    title: 'Navigation item hidden',
    description: 'Управляет видимостью узла в effective navigation config.',
    scope: FacetedCascadeScope.Target,
    valueType: ConfigurationValueType.Boolean,
    supportsBinding: true,
    supportsEnvironmentOverride: true,
    supportsWatch: true,
    runtimeMutationPolicy: 'patch',
    defaultValue: false,
  },
  {
    facet: EndgeFacetType.Configuration,
    entityType: DomainSectionType.Navigation,
    fieldPath: 'tree[*].disabled',
    title: 'Navigation item disabled',
    description: 'Управляет интерактивностью узла: пункт виден, но неактивен для перехода.',
    scope: FacetedCascadeScope.Target,
    valueType: ConfigurationValueType.Boolean,
    supportsBinding: true,
    supportsEnvironmentOverride: true,
    supportsWatch: true,
    runtimeMutationPolicy: 'patch',
    defaultValue: false,
  },
  {
    facet: EndgeFacetType.Configuration,
    entityType: DomainSectionType.Navigation,
    fieldPath: 'tree[*].path',
    title: 'Navigation item path',
    description: 'Путь перехода для link-узла навигации.',
    scope: FacetedCascadeScope.Target,
    valueType: ConfigurationValueType.String,
    supportsBinding: true,
    supportsEnvironmentOverride: true,
    supportsWatch: true,
    runtimeMutationPolicy: 'replace',
  },
  {
    facet: EndgeFacetType.Configuration,
    entityType: DomainSectionType.Navigation,
    fieldPath: 'tree[*].routeName',
    title: 'Navigation item route name',
    description: 'Именованный маршрут для link-узла навигации.',
    scope: FacetedCascadeScope.Target,
    valueType: ConfigurationValueType.String,
    supportsBinding: true,
    supportsEnvironmentOverride: true,
    supportsWatch: true,
    runtimeMutationPolicy: 'replace',
  },
  {
    facet: EndgeFacetType.Configuration,
    entityType: DomainSectionType.Navigation,
    fieldPath: 'tree[*].children',
    title: 'Navigation item children',
    description: 'Состав дочерних узлов группы. Подходит для декларативного расширения дерева.',
    scope: FacetedCascadeScope.Target,
    valueType: ConfigurationValueType.Array,
    supportsBinding: true,
    supportsEnvironmentOverride: true,
    supportsWatch: true,
    runtimeMutationPolicy: 'replace',
  },
]
