import type { PresentationContract } from '@/domain/types/configuration/faceted-cascade'

import {
  EndgeFacetType,
  FacetedCascadeEntityType,
  FacetedCascadeScope,
  PresentationContractKind,
} from '@/domain/types/configuration/faceted-cascade'

export const COMPONENT_PRESENTATION_CONTRACTS: PresentationContract<FacetedCascadeEntityType>[] = [
  {
    facet: EndgeFacetType.Presentation,
    entityType: FacetedCascadeEntityType.Component,
    role: 'body',
    title: 'Component body',
    description: 'Основной слот представления компонента. Через него подменяется основное тело renderer-компонента.',
    contractKind: PresentationContractKind.Renderer,
    scope: FacetedCascadeScope.Owner,
    supportsEnvironmentOverride: true,
  },
  {
    facet: EndgeFacetType.Presentation,
    entityType: FacetedCascadeEntityType.Component,
    role: 'header',
    title: 'Component header',
    description: 'Слот подмены header-области компонента.',
    contractKind: PresentationContractKind.Layout,
    scope: FacetedCascadeScope.Owner,
    supportsEnvironmentOverride: true,
  },
  {
    facet: EndgeFacetType.Presentation,
    entityType: FacetedCascadeEntityType.Component,
    role: 'footer',
    title: 'Component footer',
    description: 'Слот подмены footer-области компонента.',
    contractKind: PresentationContractKind.Layout,
    scope: FacetedCascadeScope.Owner,
    supportsEnvironmentOverride: true,
  },
  {
    facet: EndgeFacetType.Presentation,
    entityType: FacetedCascadeEntityType.Component,
    role: 'loading',
    title: 'Component loading',
    description: 'Слот подмены loading-состояния компонента.',
    contractKind: PresentationContractKind.State,
    scope: FacetedCascadeScope.Owner,
    supportsEnvironmentOverride: true,
  },
  {
    facet: EndgeFacetType.Presentation,
    entityType: FacetedCascadeEntityType.Component,
    role: 'empty',
    title: 'Component empty',
    description: 'Слот подмены empty-состояния компонента.',
    contractKind: PresentationContractKind.State,
    scope: FacetedCascadeScope.Owner,
    supportsEnvironmentOverride: true,
  },
  {
    facet: EndgeFacetType.Presentation,
    entityType: FacetedCascadeEntityType.Component,
    role: 'error',
    title: 'Component error',
    description: 'Слот подмены error-состояния компонента.',
    contractKind: PresentationContractKind.State,
    scope: FacetedCascadeScope.Owner,
    supportsEnvironmentOverride: true,
  },
]
