import type { PresentationContract } from '@/domain/types/configuration/faceted-cascade'

import {
  EndgeFacetType,
  FacetedCascadeEntityType,
  FacetedCascadeScope,
  PresentationContractKind,
} from '@/domain/types/configuration/faceted-cascade'

export const PAGE_PRESENTATION_CONTRACTS: PresentationContract<FacetedCascadeEntityType>[] = [
  {
    facet: EndgeFacetType.Presentation,
    entityType: FacetedCascadeEntityType.Page,
    role: 'main',
    title: 'Page main',
    description: 'Основной слот представления страницы. Через него можно подменять главный renderer или layout страницы.',
    contractKind: PresentationContractKind.Renderer,
    scope: FacetedCascadeScope.Owner,
    supportsEnvironmentOverride: true,
  },
  {
    facet: EndgeFacetType.Presentation,
    entityType: FacetedCascadeEntityType.Page,
    role: 'header',
    title: 'Page header',
    description: 'Слот подмены header-зоны страницы.',
    contractKind: PresentationContractKind.Layout,
    scope: FacetedCascadeScope.Owner,
    supportsEnvironmentOverride: true,
  },
  {
    facet: EndgeFacetType.Presentation,
    entityType: FacetedCascadeEntityType.Page,
    role: 'footer',
    title: 'Page footer',
    description: 'Слот подмены footer-зоны страницы.',
    contractKind: PresentationContractKind.Layout,
    scope: FacetedCascadeScope.Owner,
    supportsEnvironmentOverride: true,
  },
  {
    facet: EndgeFacetType.Presentation,
    entityType: FacetedCascadeEntityType.Page,
    role: 'loading',
    title: 'Page loading',
    description: 'Слот подмены состояния загрузки страницы.',
    contractKind: PresentationContractKind.State,
    scope: FacetedCascadeScope.Owner,
    supportsEnvironmentOverride: true,
  },
  {
    facet: EndgeFacetType.Presentation,
    entityType: FacetedCascadeEntityType.Page,
    role: 'empty',
    title: 'Page empty',
    description: 'Слот подмены empty-состояния страницы.',
    contractKind: PresentationContractKind.State,
    scope: FacetedCascadeScope.Owner,
    supportsEnvironmentOverride: true,
  },
  {
    facet: EndgeFacetType.Presentation,
    entityType: FacetedCascadeEntityType.Page,
    role: 'error',
    title: 'Page error',
    description: 'Слот подмены error-состояния страницы.',
    contractKind: PresentationContractKind.State,
    scope: FacetedCascadeScope.Owner,
    supportsEnvironmentOverride: true,
  },
]
