/* eslint-disable perfectionist/sort-exports -- Публичный API сгруппирован вручную по архитектурным разделам. */

//
// FEDERATION FRAMEWORK
//

export * from '@/features/federation/EndgeFederation'
export * from '@/features/federation/EndgeModule'
export * from '@/features/federation/services/EndgeModuleController'
export * from '@/features/federation/services/EndgeSlotRegistry'
export * from '@/features/federation/types/endge-modules.types'
export * from '@/features/federation/constants/federation.constants'
export * from '@/features/federation/types/federation.types'

//
// CORE IMPLEMENTATION И ВЛАДЕЛЬЦЫ МОДУЛЕЙ
//

export * from '@/features/core/kernel/endge'
export * from '@/features/core/modules/domain/EndgeDomain_Module'
export * from '@/features/core/modules/document-import/EndgeDocumentImport_Module'
export { EndgeDomainRepository_Module, EndgeDomainRepositoryReadOnlyError } from '@/features/core/modules/domain-repository/EndgeDomainRepository_Module'
export * from '@/features/core/modules/EndgeTypes_Module'
export * from '@/features/core/modules/domain/resolved/resolved-entity-index'
export * from '@/features/core/modules/implementations/EndgeImplementations_Module'
export * from '@/features/core/modules/program/EndgeProgram_Module'
export * from '@/features/core/modules/compiler/EndgeCompiler_Module'
export * from '@/features/core/modules/source/EndgeSource_Module'
export * from '@/features/core/modules/mock/EndgeMock_Module'
export * from '@/features/core/modules/runtime/execution/endge-composition'
export * from '@/features/core/modules/runtime/execution/endge-project'
export * from '@/features/core/modules/runtime/execution/endge-data-view'
export * from '@/features/core/modules/runtime/execution/endge-response-output'
export * from '@/features/core/modules/runtime/execution/endge-query'
export * from '@/features/core/modules/computations/EndgeComputations_Module'
export * from '@/features/core/modules/computations/model/ComputationResource'
export * from '@/features/core/modules/computations/model/ComputationResourceRegistry'
export * from '@/features/core/modules/computations/services/ComputationGraphExecutor'
export * from '@/features/core/modules/converters/EndgeConverters_Module'
export * from '@/features/core/modules/runtime/operation/operation-history'
export * from '@/features/core/modules/runtime/operation/EndgeOperations_Module'
export * from '@/features/core/modules/runtime/EndgeRuntime_Module'
export * from '@/features/core/modules/auth/EndgeAuth_Module'
export * from '@/features/core/modules/auth/domain/AuthInteractionRequiredError'
export * from '@/features/core/modules/auth/adapters/OidcBrowserSession_Adapter'
export * from '@/features/core/modules/i18n/EndgeI18n_Module'
export * from '@/features/core/modules/workspace/EndgeWorkspace_Module'
export * from '@/features/core/modules/context/endge-vars'
export * from '@/features/core/modules/diagnostics/EndgeDiagnostics_Module'
export * from '@/features/core/modules/diagnostics/EndgeProblems_Module'
export * from '@/features/core/modules/diagnostics/EndgeTelemetry_Module'
export * from '@/features/core/modules/context/EndgeContext_Module'
export * from '@/features/core/modules/configuration/EndgeConfiguration_Module'
export * from '@/features/core/modules/configuration/EndgeConfigurationSchema_Module'
export * from '@/features/core/modules/actions/EndgeActions_Module'
export * from '@/features/core/modules/ui/EndgeUI_Module'
export * from '@/features/core/modules/ui/EndgeUIRegistry_Module'
export * from '@/features/core/modules/styles/EndgeStyles_Module'
export * from '@/features/core/modules/diagnostics/domain/entities/DiagnosticsRecordStore'
export * from '@/features/core/modules/diagnostics/domain/entities/DiagnosticsSpan'

//
// ПУБЛИЧНЫЕ КОНТРАКТЫ
//

export * from '@/features/core/modules/auth/domain/types/auth-profile.types'
export * from '@/features/core/modules/domain/types/component/component-core.types'
export * from '@/features/core/modules/domain/types/component/component.types'
export * from '@/features/core/modules/domain/types/component/sfc/source.types'
export * from '@/features/core/modules/domain/types/component/sfc/table-visibility.types'
export * from '@/features/core/modules/domain/types/component/sfc/table-events.types'
export * from '@/features/core/modules/domain/types/component/sfc/intrinsic-events.types'
export * from '@/features/core/modules/domain/types/component/sfc/tag-input-contract.types'
export * from '@/features/core/modules/domain/types/component/sfc/tag-attribute-contract.types'
export * from '@/features/core/modules/domain/types/component/sfc/location.types'
export * from '@/features/core/modules/domain/types/component/sfc/ast.types'
export * from '@/features/core/modules/domain/types/component/sfc/ir.types'
export * from '@/features/core/modules/domain/types/component/sfc/dependencies.types'
export * from '@/features/core/modules/domain/types/component/sfc/ports.types'
export * from '@/features/core/modules/domain/types/component/sfc/ports-source.types'
export * from '@/features/core/modules/domain/types/component/sfc/props-visual.types'
export * from '@/features/core/modules/domain/types/component/sfc/metadata-visual.types'
export * from '@/features/core/modules/domain/types/component/sfc/visual-projection.types'
export * from '@/features/core/modules/configuration/domain/types/configuration.type'
export * from '@/features/core/modules/domain/types/computation/computation.types'
export * from '@/features/core/modules/diagnostics/domain/types/diagnostics-adapter.type'
export * from '@/features/core/modules/diagnostics/domain/types/diagnostics.types'
export * from '@/features/core/modules/domain/types/document/codegen.types'
export * from '@/features/core/modules/domain/types/document/document.types'
export * from '@/features/core/modules/domain/types/document/document-create.type'
export * from '@/features/core/modules/domain/types/document/document-draft.type'
export * from '@/features/core/modules/domain/types/document/document-move.type'
export * from '@/features/core/modules/domain/types/document/domain-export.type'
export * from '@/features/core/modules/domain/types/document/domain-provider.type'
export * from '@/features/core/modules/domain/types/document/domain-snapshot.type'
export * from '@/features/core/modules/domain/types/document/entity-management.type'
export * from '@/features/core/modules/document-import/domain/types/document-import.type'
export * from '@/features/core/modules/domain/types/document/filter.types'
export * from '@/features/core/modules/domain/types/document/navigation.types'
export * from '@/features/core/modules/domain/types/document/query.types'
export * from '@/features/core/modules/workspace/domain/workspace.types'
export * from '@/features/core/kernel/types/bootstrap.types'
export * from '@/features/core/modules/events/domain/events.types'
export * from '@/features/core/modules/mock/domain/types/mock-data.type'
export * from '@/features/core/modules/program/domain/types/program.types'
export * from '@/features/core/modules/program/domain/types/action-program.types'
export * from '@/features/core/modules/program/domain/types/program-metadata.types'
export * from '@/features/core/modules/actions/domain/action.types'
export * from '@/features/core/modules/runtime/domain/vocab-cache.types'
export * from '@/features/core/modules/implementations/domain/implementation.types'
export * from '@/features/core/modules/source/domain/types/action-source.types'
export * from '@/features/core/modules/context/domain/context-persistence.types'
export * from '@/features/core/modules/runtime/domain/execution-context.types'
export * from '@/features/core/modules/runtime/domain/query-execution.types'
export * from '@/features/core/modules/runtime/domain/runtime-entity-map.types'
export * from '@/features/core/modules/runtime/domain/runtime-host.types'
export * from '@/features/core/modules/runtime/domain/runtime-execute.type'
export * from '@/features/core/modules/runtime/domain/runtime-registry.types'
export * from '@/features/core/modules/runtime/domain/runtime-resource.types'
export * from '@/features/core/modules/runtime/domain/runtime-scope.types'
export * from '@/features/core/modules/runtime/domain/sfc-render-inspection.type'
export * from '@/features/core/modules/runtime/domain/runtime-project-session.types'
export * from '@/features/core/modules/runtime/domain/runtime-strategy.types'
export * from '@/features/core/modules/runtime/domain/runtime.types'
export * from '@/features/core/modules/runtime/domain/table-binding.types'
export * from '@/features/core/modules/runtime/domain/table.types'
export * from '@/features/core/modules/source/domain/types/composition-source.types'
export * from '@/features/core/modules/source/domain/types/data-view-source.types'
export * from '@/features/core/modules/source/domain/types/filter-source.types'
export * from '@/features/core/modules/source/domain/types/query-source.types'
export * from '@/features/core/modules/source/domain/types/response-output.types'
export * from '@/features/core/modules/source/domain/types/vocab-source.types'
export * from '@/features/core/modules/source/domain/types/source-engine.types'
export * from '@/features/core/modules/source/domain/types/source-expression.types'
export * from '@/features/core/modules/source/domain/types/store-source.types'
export * from '@/features/core/modules/source/domain/types/stream-source.types'
export * from '@/features/core/modules/source/domain/types/update-source.types'
export * from '@/features/core/modules/source/domain/types/type-source.types'
export * from '@/features/core/modules/source/domain/types/configuration-source.types'
export * from '@/features/core/modules/styles/domain/types/style.types'
export * from '@/features/core/modules/ui/domain/types/context-menu.types'
export * from '@/features/core/modules/source/domain/types/filter-view.type'
export * from '@/features/core/modules/ui/domain/types/jsx.types'
export * from '@/features/core/modules/ui/domain/types/ui-composition.types'
export * from '@/features/core/modules/ui/domain/types/ui-render-adapter.type'
export * from '@/features/core/modules/ui/domain/types/tooltip-markdown.types'
export * from '@/features/core/modules/ui/domain/types/ui.types'
export * from '@/features/core/modules/i18n/domain/i18n.types'

//
// ДОМЕННЫЕ И RUNTIME-СУЩНОСТИ
//

export * from '@/features/core/modules/domain/entities/RAction'
export * from '@/features/core/modules/domain/entities/RComponent'
export * from '@/features/core/modules/domain/entities/RComponentBase'
export * from '@/features/core/modules/domain/entities/RComponentCore'
export * from '@/features/core/modules/domain/entities/RComponentSFC'
export * from '@/features/core/modules/domain/entities/RQuery'
export * from '@/features/core/modules/domain/entities/RDataView'
export * from '@/features/core/modules/domain/entities/RComposition'
export * from '@/features/core/modules/domain/entities/RStore'
export * from '@/features/core/modules/domain/entities/RStream'
export * from '@/features/core/modules/domain/entities/RUpdate'
export * from '@/features/core/modules/domain/entities/RMock'
export * from '@/features/core/modules/domain/entities/RQueryFilter'
export * from '@/features/core/modules/domain/entities/RType'
export * from '@/features/core/modules/domain/entities/RComponentDSL'
export * from '@/features/core/modules/domain/entities/RComponentTable'
export * from '@/features/core/modules/domain/entities/RComponentTableColumn'
export * from '@/features/core/modules/domain/entities/RConverter'
export * from '@/features/core/modules/domain/entities/RComputation'
export * from '@/features/core/modules/domain/entities/RIntegration'
export * from '@/features/core/modules/domain/entities/REnvironment'
export * from '@/features/core/modules/domain/entities/RTenant'
export * from '@/features/core/modules/domain/entities/RPolicy'
export * from '@/features/core/modules/domain/entities/RStyle'
export * from '@/features/core/modules/domain/entities/RConfiguration'
export * from '@/features/core/modules/domain/entities/RVocabs'
export * from '@/features/core/modules/domain/entities/RAuthProfile'
export * from '@/features/core/modules/domain/entities/RI18nBundle'
export * from '@/features/core/modules/domain/entities/RWorkspace'
export * from '@/features/core/modules/domain/entities/REntity'
export * from '@/features/core/modules/runtime/RuntimeBindingScope'
export * from '@/features/core/modules/runtime/RuntimeActionRegistry'
export * from '@/features/core/modules/runtime/hosts/FilterViewRuntimeHost'

export * from '@/features/core/modules/domain/entities/RField'
export * from '@/features/core/modules/domain/entities/RFilter'
export * from '@/features/core/modules/domain/entities/RParameter'
export * from '@/features/core/modules/domain/entities/RProject'
export * from '@/features/core/modules/domain/entities/RFolder'
export * from '@/features/core/modules/domain/entities/RVersion'
export * from '@/features/core/modules/domain/entities/RPageTemplate'
export * from '@/features/core/modules/domain/entities/RPage'
export * from '@/features/core/modules/domain/entities/RNavigation'

export * from '@/features/core/modules/updates/tools/ScheduleUpdate-sse-generator'
export * from '@/features/core/modules/domain/component/component-sfc-edit-trigger'

export * from '@/features/core/modules/diagnostics/config/diagnostics.config'
export * from '@/features/core/modules/diagnostics/adapters/ConsoleDiagnosticsAdapter'
export * from '@/features/core/modules/diagnostics/adapters/DiagnosticsAdapterRegistry'
export * from '@/features/core/modules/diagnostics/adapters/SentryDiagnosticsAdapter'
export * from '@/features/core/modules/diagnostics/adapters/SentryDiagnosticsAdapter.types'
export * from '@/features/core/kernel/config/kernel.config'
export * from '@/features/core/modules/ui/ui-composition.config'
export * from '@/features/core/modules/configuration/domain/tooltip.config'
export { default as Config } from '@/features/core/kernel/config/kernel.config'

export * from '@/features/core/modules/context/persistence/EndgeStorageAdapterRegistry'
export * from '@/features/core/modules/context/persistence/RuntimeStateController'
export * from '@/features/core/modules/context/persistence/adapters/DisabledContextAdapter'
export * from '@/features/core/modules/context/persistence/adapters/LocalStorageContextAdapter'

export * from '@/features/core/modules/converters/tools/date/string-to-date'
export * from '@/features/core/modules/converters/tools/date/weekdays-range'

export * from '@/features/core/modules/domain/documents/domain-document-descriptors'
export * from '@/features/core/modules/domain/documents/service-document-serializer'
export * from '@/features/core/modules/configuration/domain/endge-configuration'
export * from '@/features/core/modules/configuration/domain/configuration-value'
export * from '@/features/core/modules/source/services/compilers/configuration-source-compile'
export * from '@/features/core/modules/ui/tooltip/endge-tooltip-markdown'
export * from '@/features/core/modules/i18n/services/composition-i18n-catalog-projection'

export * from '@/features/core/modules/runtime/RuntimeHostBase'
export * from '@/features/core/modules/runtime/RuntimeHostRegistry'
export * from '@/features/core/modules/runtime/RuntimeAppScope'
export * from '@/features/core/modules/runtime/RuntimeScope'
export * from '@/features/core/modules/runtime/EndgeRuntimeScopes_Module'
export * from '@/features/core/modules/runtime/RuntimeResourceBag'
export * from '@/features/core/modules/runtime/RuntimeHostFactory'
export * from '@/features/core/modules/runtime/hosts/ProjectRuntimeHost'
export * from '@/features/core/modules/runtime/hosts/PageRuntimeHost'
export * from '@/features/core/modules/runtime/hosts/ComponentSFCRuntimeHost'
export * from '@/features/core/modules/runtime/ComponentSFCEventBoundary'
export * from '@/features/core/modules/runtime/hosts/QueryRuntimeHost'
export * from '@/features/core/modules/runtime/hosts/FilterRuntimeHost'
export * from '@/features/core/modules/runtime/hosts/CompositionRuntimeHost'
export * from '@/features/core/modules/runtime/hosts/StoreRuntimeHost'
export * from '@/features/core/modules/runtime/hosts/ActionRuntimeHost'

export * from '@/features/core/modules/compiler/services/component-sfc/component-sfc-compile'
export * from '@/features/core/modules/compiler/services/component-sfc/component-sfc-attributes'
export * from '@/features/core/modules/compiler/services/component-sfc/component-sfc-expression'
export * from '@/features/core/modules/compiler/services/component-sfc/component-sfc-parse'
export * from '@/features/core/modules/compiler/services/component-sfc/component-sfc-script'
export * from '@/features/core/modules/domain/component/sfc/component-sfc-source-parts'
export * from '@/features/core/modules/compiler/services/component-sfc/component-sfc-style'
export * from '@/features/core/modules/compiler/services/component-sfc/component-sfc-table-menu'
export * from '@/features/core/modules/compiler/services/component-sfc/component-sfc-table-pin'
export * from '@/features/core/modules/compiler/services/component-sfc/component-sfc-table-sort'
export * from '@/features/core/modules/compiler/services/component-sfc/component-sfc-table-visibility'
export * from '@/features/core/modules/compiler/services/component-sfc/component-sfc-template'
export * from '@/features/core/modules/compiler/services/component-sfc/component-sfc-ports'
export * from '@/features/core/modules/compiler/services/component-sfc/component-sfc-forward'
export * from '@/features/core/modules/compiler/services/computation/computation-compile'
export * from '@/features/core/modules/styles/services/endgecss-compile'
export * from '@/features/core/modules/styles/services/endgecss-match'
export * from '@/features/core/modules/source/services/source-expression-evaluate'
export * from '@/features/core/modules/source/services/filter-source-patch'
export * from '@/features/core/modules/source/services/vocab-source-patch'
export * from '@/features/core/modules/source/services/compilers/vocab-source-compile'
export * from '@/features/core/modules/source/services/type-source-serialize'
export * from '@/features/core/modules/source/services/configuration-source-patch'
export * from '@/features/core/modules/source/services/typescript-type-source'
export * from '@/features/core/modules/source/services/component-sfc/component-sfc-visual-projection'
export * from '@/features/core/modules/source/services/component-sfc/component-sfc-table-source-patch'
export * from '@/features/core/modules/source/services/component-sfc/component-sfc-ports-source-patch'
export * from '@/features/core/modules/source/services/component-sfc/component-sfc-props-source-patch'
export * from '@/features/core/modules/source/services/component-sfc/component-sfc-metadata-source-patch'
export * from '@/features/core/modules/runtime/services/RuntimeStrategyRegistry'
export * from '@/features/core/modules/runtime/services/SFCRenderInspectionSession'
export * from '@/features/core/modules/actions/services/table-actions'
export * from '@/features/core/modules/runtime/services/strategies/ActionRuntimeStrategy'
export * from '@/features/core/modules/runtime/services/strategies/ComponentSFCRuntimeStrategy'
export * from '@/features/core/modules/runtime/services/strategies/PageRuntimeStrategy'
export * from '@/features/core/modules/runtime/services/strategies/ProjectRuntimeStrategy'
export * from '@/features/core/modules/runtime/services/strategies/QueryRuntimeStrategy'
export * from '@/features/core/modules/runtime/services/strategies/FilterRuntimeStrategy'
export * from '@/features/core/modules/runtime/services/strategies/CompositionRuntimeStrategy'
export * from '@/features/core/modules/runtime/services/strategies/StoreRuntimeStrategy'
export * from '@/features/core/modules/runtime/services/strategies/StreamRuntimeStrategy'
export * from '@/features/core/modules/runtime/hosts/StreamRuntimeHost'
export * from '@/features/core/modules/runtime/domain/stream-runtime.types'
